// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	UserId           uint64 `json:"userId"`
	ProductId        uint64 `json:"productId"`
	ShoppingCartItem string `json:"shoppingCartItem"`
}

type CountResp struct {
	Count uint64 `json:"count"`
}

type DeleteItemReq struct {
	UserId    uint64 `json:"userId"`
	ProductId uint64 `json:"productId"`
}

type DeleteItemsReq struct {
	UserId    uint64   `json:"userId"`
	ProductId []uint64 `json:"productId"`
}

type GetItemsResp struct {
	Items []string `json:"items"`
}

type IdReq struct {
	Id uint64 `path:"id"`
}

type ShoppingCartItem struct {
	ProductId uint64  `json:"productId"`
	Picture   string  `json:"picture"`
	Title     string  `json:"title"`
	Stock     uint64  `json:"stock"`
	Price     float64 `json:"price"`
	Quantity  uint64  `json:"quantity"`
	Total     float64 `json:"total"`
}
