// Code generated by goctl. DO NOT EDIT.
// Source: database.proto

package server

import (
	"context"

	"server-v1/service/database/internal/logic/productservice"
	"server-v1/service/database/internal/svc"
	"server-v1/service/database/pb/databaseService"
)

type ProductServiceServer struct {
	svcCtx *svc.ServiceContext
	databaseService.UnimplementedProductServiceServer
}

func NewProductServiceServer(svcCtx *svc.ServiceContext) *ProductServiceServer {
	return &ProductServiceServer{
		svcCtx: svcCtx,
	}
}

// 根据id获取商品信息
func (s *ProductServiceServer) GetProductById(ctx context.Context, in *databaseService.IdRequest) (*databaseService.Product, error) {
	l := productservicelogic.NewGetProductByIdLogic(ctx, s.svcCtx)
	return l.GetProductById(in)
}
