// Code generated by goctl. DO NOT EDIT.
// Source: user_rpc.proto

package accountservice

import (
	"context"

	"server-v1/service/user/pb/user_db_service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Account               = user_db_service.Account
	GetAccountByIdRequest = user_db_service.GetAccountByIdRequest

	AccountService interface {
		GetAccountById(ctx context.Context, in *GetAccountByIdRequest, opts ...grpc.CallOption) (*Account, error)
	}

	defaultAccountService struct {
		cli zrpc.Client
	}
)

func NewAccountService(cli zrpc.Client) AccountService {
	return &defaultAccountService{
		cli: cli,
	}
}

func (m *defaultAccountService) GetAccountById(ctx context.Context, in *GetAccountByIdRequest, opts ...grpc.CallOption) (*Account, error) {
	client := user_db_service.NewAccountServiceClient(m.cli.Conn())
	return client.GetAccountById(ctx, in, opts...)
}
