version: '3'

services:
  redis:
    image: redis:latest
    container_name: myRedis-container
    ports:
      - "6379:6379"
    volumes:
      - /path/on/host:/var/lib/myRedis

  # 注意mysql8以上，默认不允许非主机使用root权限登录，需要修改配置文件
  # 首先使用docker exec -it mysql_server mysql -u root -p 进入mysql
  # 然后使用UPDATE user SET Host = '%' WHERE User = 'root' AND Host = 'localhost';
  # 最后使用FLUSH PRIVILEGES;刷新权限
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - /data/docker/mysql:/var/lib/mysql

  etcd:
    image: bitnami/etcd:3.5.13
    container_name: etcd-container
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"