version: '3'

services:
  redis:
    image: redis:latest
    container_name: myRedis-container
    ports:
      - "6379:6379"
    volumes:
      - /path/on/host:/var/lib/myRedis

  # 注意mysql8以上，默认不允许非主机使用root权限登录，需要修改配置文件
  # 首先使用docker exec -it mysql_server mysql -u root -p 进入mysql
  # 然后使用UPDATE user SET Host = '%' WHERE User = 'root' AND Host = 'localhost';
  # 最后使用FLUSH PRIVILEGES;刷新权限
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - /data/docker/mysql:/var/lib/mysql

  etcd:
    image: bitnami/etcd:3.5.13
    container_name: etcd-container
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"

#  # apisix
#  apisix:
#    image: apache/apisix:${APISIX_IMAGE_TAG:-3.9.0-debian}
#    container_name: apisix-container
#    restart: always
#    volumes:
#      - ./script/apisix_config/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
#    depends_on:
#      - apisix-etcd
#    ##network_mode: host
#    ports:
#      - "9180:9180/tcp"
#      - "9080:9080/tcp"
#      - "9091:9091/tcp"
#      - "9443:9443/tcp"
#      - "9092:9092/tcp"
#    networks:
#      apisix:
#
#  prometheus:
#    image: prom/prometheus:v2.25.0
#    container_name: prometheus-container
#    restart: always
#    volumes:
#      - ./script/apisix_config/prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    networks:
#      apisix:
#
#  grafana:
#    image: grafana/grafana:7.3.7
#    container_name: grafana-container
#    restart: always
#    ports:
#      - "3000:3000"
#    volumes:
#      - "./script/apisix_config/grafana_conf/provisioning:/etc/grafana/provisioning"
#      - "./script/apisix_config/grafana_conf/dashboards:/var/lib/grafana/dashboards"
#      - "./script/apisix_config/grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
#    networks:
#      apisix:
#
#  apisix-etcd:
#    image: bitnami/etcd:3.5.11
#    container_name: apisix-etcd-container
#    restart: always
#    volumes:
#      - etcd_data:/bitnami/etcd
#    environment:
#      ETCD_ENABLE_V2: "true"
#      ALLOW_NONE_AUTHENTICATION: "yes"
#      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
#      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
#    ports:
#      - "2379:2379/tcp"
#    networks:
#      apisix:
#
#
#networks:
#  apisix:
#    driver: bridge
#  go-zero:
#    driver: bridge
#
#volumes:
#  etcd_data:
#    driver: local