// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"server-v1/restful/shoppingCart/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/item",
				Handler: AddItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/item",
				Handler: UpdateItemHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/item",
				Handler: DeleteItemHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/items",
				Handler: DeleteItemsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/items/:id",
				Handler: GetItemsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/shoppingCart/v1"),
	)
}
