// Code generated by goctl. DO NOT EDIT.
// Source: database.proto

package server

import (
	"context"

	"server-v1/service/database/internal/logic/orderservice"
	"server-v1/service/database/internal/svc"
	"server-v1/service/database/pb/databaseService"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	databaseService.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 根据id获取订单信息
func (s *OrderServiceServer) GetOrderById(ctx context.Context, in *databaseService.IdRequest) (*databaseService.Order, error) {
	l := orderservicelogic.NewGetOrderByIdLogic(ctx, s.svcCtx)
	return l.GetOrderById(in)
}
