// Code generated by goctl. DO NOT EDIT.
// Source: database.proto

package orderservice

import (
	"context"

	"server-v1/service/database/pb/databaseService"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Account             = databaseService.Account
	AccountRequest      = databaseService.AccountRequest
	BoolResp            = databaseService.BoolResp
	IdRequest           = databaseService.IdRequest
	Order               = databaseService.Order
	Product             = databaseService.Product
	UpdateIntRequest    = databaseService.UpdateIntRequest
	UpdateStringRequest = databaseService.UpdateStringRequest

	OrderService interface {
		// 根据id获取订单信息
		GetOrderById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Order, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 根据id获取订单信息
func (m *defaultOrderService) GetOrderById(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Order, error) {
	client := databaseService.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrderById(ctx, in, opts...)
}
